name: CloudKart Dependency Scan

on:
  push:
    branches:
      - feat/devops-cicd
  pull_request:
    branches:
      - feat/devops-cicd

jobs:
  dependency-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Security audit
        run: npm audit --audit-level=high