name: CloudKart Secret Scan

on:
  push:
    branches:
      - feat/devops-cicd
  pull_request:
    branches:
      - feat/devops-cicd

jobs:
  secret-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}